
/* File generated by gen_cfile.py. Should not be modified. */

#include "Master.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS16 motor1_control = 0x0;		/* Mapped at index 0x3000, subindex 0x00 */
UNS16 motor1_status = 0x0;		/* Mapped at index 0x3001, subindex 0x00 */
INTEGER8 motor1_mode = 0x0;		/* Mapped at index 0x3002, subindex 0x00 */
INTEGER8 motor1_mode_display = 0x0;		/* Mapped at index 0x3003, subindex 0x00 */
INTEGER32 motor1_position = 0x0;		/* Mapped at index 0x3004, subindex 0x00 */
INTEGER32 motor1_velocity = 0x0;		/* Mapped at index 0x3005, subindex 0x00 */
UNS16 motor2_control = 0x0;		/* Mapped at index 0x3006, subindex 0x00 */
UNS16 motor2_status = 0x0;		/* Mapped at index 0x3007, subindex 0x00 */
INTEGER8 motor2_mode = 0x0;		/* Mapped at index 0x3008, subindex 0x00 */
INTEGER8 motor2_mode_display = 0x0;		/* Mapped at index 0x3009, subindex 0x00 */
INTEGER32 motor2_position = 0x0;		/* Mapped at index 0x3010, subindex 0x00 */
INTEGER32 motor2_velocity = 0x0;		/* Mapped at index 0x3011, subindex 0x00 */
UNS16 motor3_control = 0x0;		/* Mapped at index 0x3012, subindex 0x00 */
UNS16 motor3_status = 0x0;		/* Mapped at index 0x3013, subindex 0x00 */
INTEGER8 motor3_mode = 0x0;		/* Mapped at index 0x3014, subindex 0x00 */
INTEGER8 motor3_mode_display = 0x0;		/* Mapped at index 0x3015, subindex 0x00 */
INTEGER32 motor3_position = 0x0;		/* Mapped at index 0x3016, subindex 0x00 */
INTEGER32 motor3_velocity = 0x0;		/* Mapped at index 0x3017, subindex 0x00 */
UNS16 motor4_control = 0x0;		/* Mapped at index 0x3018, subindex 0x00 */
UNS16 motor4_status = 0x0;		/* Mapped at index 0x3019, subindex 0x00 */
INTEGER8 motor4_mode = 0x0;		/* Mapped at index 0x3020, subindex 0x00 */
INTEGER8 motor4_mode_display = 0x0;		/* Mapped at index 0x3021, subindex 0x00 */
INTEGER32 motor4_position = 0x0;		/* Mapped at index 0x3022, subindex 0x00 */
INTEGER32 motor4_velocity = 0x0;		/* Mapped at index 0x3023, subindex 0x00 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 Master_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 Master_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 Master_iam_a_slave = 0;

TIMER_HANDLE Master_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 Master_obj1000 = 0x0;	/* 0 */
                    subindex Master_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1000, NULL }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 Master_obj1001 = 0x0;	/* 0 */
                    subindex Master_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_obj1001, NULL }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 Master_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 Master_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    subindex Master_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1003, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1003[0], NULL }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 Master_obj1005 = 0x40000080;	/* 1073741952 */
                    subindex Master_Index1005[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1005, NULL }
                     };

/* index 0x1006 :   Communication / Cycle Period. */
                    UNS32 Master_obj1006 = 0x3D090;	/* 250000 */
                    subindex Master_Index1006[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1006, NULL }
                     };

/* index 0x100C :   Guard Time */ 
                    UNS16 Master_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 Master_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID. */
                    UNS32 Master_obj1014 = 0x80;	/* 128 */
                    subindex Master_Index1014[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1014, NULL }
                     };

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 Master_highestSubIndex_obj1016 = 0;
                    UNS32 Master_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time */ 
                    UNS16 Master_obj1017 = 0x0;   /* 0 */

/* index 0x1018 :   Identity. */
                    UNS8 Master_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 Master_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 Master_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 Master_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 Master_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex Master_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1018, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1018_Vendor_ID, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1018_Product_Code, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1018_Revision_Number, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1018_Serial_Number, NULL }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 Master_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1400_COB_ID_used_by_PDO = 0x181;	/* 385 */
                    UNS8 Master_obj1400_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 Master_obj1400_Inhibit_Time = 0xA;	/* 10 */
                    UNS8 Master_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1400, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1400_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1400_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1400_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1400_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1400_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1400_SYNC_start_value, NULL }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 Master_highestSubIndex_obj1401 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1401_COB_ID_used_by_PDO = 0x282;	/* 642 */
                    UNS8 Master_obj1401_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 Master_obj1401_Inhibit_Time = 0xA;	/* 10 */
                    UNS8 Master_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1401_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1401_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1401, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1401_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1401_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1401_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1401_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1401_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1401_SYNC_start_value, NULL }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 Master_highestSubIndex_obj1402 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1402_COB_ID_used_by_PDO = 0x383;	/* 899 */
                    UNS8 Master_obj1402_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 Master_obj1402_Inhibit_Time = 0xA;	/* 10 */
                    UNS8 Master_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1402_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1402_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1402, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1402_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1402_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1402_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1402_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1402_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1402_SYNC_start_value, NULL }
                     };

/* index 0x1403 :   Receive PDO 4 Parameter. */
                    UNS8 Master_highestSubIndex_obj1403 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1403_COB_ID_used_by_PDO = 0x484;	/* 1156 */
                    UNS8 Master_obj1403_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 Master_obj1403_Inhibit_Time = 0xA;	/* 10 */
                    UNS8 Master_obj1403_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1403_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1403_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1403[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1403, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1403_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1403_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1403_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1403_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1403_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1403_SYNC_start_value, NULL }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 Master_highestSubIndex_obj1600 = 3; /* number of subindex - 1*/
                    UNS32 Master_obj1600[] = 
                    {
                      0x30010010,	/* 805371920 */
                      0x30030008,	/* 805502984 */
                      0x30040020	/* 805568544 */
                    };
                    subindex Master_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1600, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1600[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1600[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1600[2], NULL }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 Master_highestSubIndex_obj1601 = 3; /* number of subindex - 1*/
                    UNS32 Master_obj1601[] = 
                    {
                      0x30070010,	/* 805765136 */
                      0x30090008,	/* 805896200 */
                      0x30100020	/* 806354976 */
                    };
                    subindex Master_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1601, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1601[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1601[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1601[2], NULL }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 Master_highestSubIndex_obj1602 = 3; /* number of subindex - 1*/
                    UNS32 Master_obj1602[] = 
                    {
                      0x30130010,	/* 806551568 */
                      0x30150008,	/* 806682632 */
                      0x30160020	/* 806748192 */
                    };
                    subindex Master_Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1602, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1602[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1602[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1602[2], NULL }
                     };

/* index 0x1603 :   Receive PDO 4 Mapping. */
                    UNS8 Master_highestSubIndex_obj1603 = 3; /* number of subindex - 1*/
                    UNS32 Master_obj1603[] = 
                    {
                      0x30190010,	/* 806944784 */
                      0x30210008,	/* 807469064 */
                      0x30220020	/* 807534624 */
                    };
                    subindex Master_Index1603[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1603, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1603[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1603[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1603[2], NULL }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 Master_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1800_COB_ID_used_by_PDO = 0x201;	/* 513 */
                    UNS8 Master_obj1800_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 Master_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1800_Event_Timer = 0x64;	/* 100 */
                    UNS8 Master_obj1800_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1800, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1800_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1800_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1800_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1800_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1800_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1800_SYNC_start_value, NULL }
                     };

/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 Master_highestSubIndex_obj1801 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1801_COB_ID_used_by_PDO = 0x302;	/* 770 */
                    UNS8 Master_obj1801_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 Master_obj1801_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1801_Event_Timer = 0x64;	/* 100 */
                    UNS8 Master_obj1801_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1801[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1801, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1801_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1801_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1801_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1801_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1801_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1801_SYNC_start_value, NULL }
                     };

/* index 0x1802 :   Transmit PDO 3 Parameter. */
                    UNS8 Master_highestSubIndex_obj1802 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1802_COB_ID_used_by_PDO = 0x403;	/* 1027 */
                    UNS8 Master_obj1802_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 Master_obj1802_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1802_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1802_Event_Timer = 0x64;	/* 100 */
                    UNS8 Master_obj1802_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1802[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1802, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1802_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1802_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1802_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1802_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1802_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1802_SYNC_start_value, NULL }
                     };

/* index 0x1803 :   Transmit PDO 4 Parameter. */
                    UNS8 Master_highestSubIndex_obj1803 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1803_COB_ID_used_by_PDO = 0x504;	/* 1284 */
                    UNS8 Master_obj1803_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 Master_obj1803_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1803_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1803_Event_Timer = 0x64;	/* 100 */
                    UNS8 Master_obj1803_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1803[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1803, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1803_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1803_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1803_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1803_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1803_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1803_SYNC_start_value, NULL }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 Master_highestSubIndex_obj1A00 = 3; /* number of subindex - 1*/
                    UNS32 Master_obj1A00[] = 
                    {
                      0x30000010,	/* 805306384 */
                      0x30020008,	/* 805437448 */
                      0x30050020	/* 805634080 */
                    };
                    subindex Master_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1A00, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A00[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A00[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A00[2], NULL }
                     };

/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 Master_highestSubIndex_obj1A01 = 3; /* number of subindex - 1*/
                    UNS32 Master_obj1A01[] = 
                    {
                      0x30060010,	/* 805699600 */
                      0x30080008,	/* 805830664 */
                      0x30110020	/* 806420512 */
                    };
                    subindex Master_Index1A01[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1A01, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A01[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A01[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A01[2], NULL }
                     };

/* index 0x1A02 :   Transmit PDO 3 Mapping. */
                    UNS8 Master_highestSubIndex_obj1A02 = 3; /* number of subindex - 1*/
                    UNS32 Master_obj1A02[] = 
                    {
                      0x30120010,	/* 806486032 */
                      0x30140008,	/* 806617096 */
                      0x30170020	/* 806813728 */
                    };
                    subindex Master_Index1A02[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1A02, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A02[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A02[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A02[2], NULL }
                     };

/* index 0x1A03 :   Transmit PDO 4 Mapping. */
                    UNS8 Master_highestSubIndex_obj1A03 = 3; /* number of subindex - 1*/
                    UNS32 Master_obj1A03[] = 
                    {
                      0x30180010,	/* 806879248 */
                      0x30200008,	/* 807403528 */
                      0x30230020	/* 807600160 */
                    };
                    subindex Master_Index1A03[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1A03, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A03[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A03[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A03[2], NULL }
                     };

/* index 0x3000 :   Mapped variable motor1_control */
                    subindex Master_Index3000[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&motor1_control, NULL }
                     };

/* index 0x3001 :   Mapped variable motor1_status */
                    subindex Master_Index3001[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&motor1_status, NULL }
                     };

/* index 0x3002 :   Mapped variable motor1_mode */
                    subindex Master_Index3002[] = 
                     {
                       { RW, int8, sizeof (INTEGER8), (void*)&motor1_mode, NULL }
                     };

/* index 0x3003 :   Mapped variable motor1_mode_display */
                    subindex Master_Index3003[] = 
                     {
                       { RW, int8, sizeof (INTEGER8), (void*)&motor1_mode_display, NULL }
                     };

/* index 0x3004 :   Mapped variable motor1_position */
                    subindex Master_Index3004[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&motor1_position, NULL }
                     };

/* index 0x3005 :   Mapped variable motor1_velocity */
                    subindex Master_Index3005[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&motor1_velocity, NULL }
                     };

/* index 0x3006 :   Mapped variable motor2_control */
                    subindex Master_Index3006[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&motor2_control, NULL }
                     };

/* index 0x3007 :   Mapped variable motor2_status */
                    subindex Master_Index3007[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&motor2_status, NULL }
                     };

/* index 0x3008 :   Mapped variable motor2_mode */
                    subindex Master_Index3008[] = 
                     {
                       { RW, int8, sizeof (INTEGER8), (void*)&motor2_mode, NULL }
                     };

/* index 0x3009 :   Mapped variable motor2_mode_display */
                    subindex Master_Index3009[] = 
                     {
                       { RW, int8, sizeof (INTEGER8), (void*)&motor2_mode_display, NULL }
                     };

/* index 0x3010 :   Mapped variable motor2_position */
                    subindex Master_Index3010[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&motor2_position, NULL }
                     };

/* index 0x3011 :   Mapped variable motor2_velocity */
                    subindex Master_Index3011[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&motor2_velocity, NULL }
                     };

/* index 0x3012 :   Mapped variable motor3_control */
                    subindex Master_Index3012[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&motor3_control, NULL }
                     };

/* index 0x3013 :   Mapped variable motor3_status */
                    subindex Master_Index3013[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&motor3_status, NULL }
                     };

/* index 0x3014 :   Mapped variable motor3_mode */
                    subindex Master_Index3014[] = 
                     {
                       { RW, int8, sizeof (INTEGER8), (void*)&motor3_mode, NULL }
                     };

/* index 0x3015 :   Mapped variable motor3_mode_display */
                    subindex Master_Index3015[] = 
                     {
                       { RW, int8, sizeof (INTEGER8), (void*)&motor3_mode_display, NULL }
                     };

/* index 0x3016 :   Mapped variable motor3_position */
                    subindex Master_Index3016[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&motor3_position, NULL }
                     };

/* index 0x3017 :   Mapped variable motor3_velocity */
                    subindex Master_Index3017[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&motor3_velocity, NULL }
                     };

/* index 0x3018 :   Mapped variable motor4_control */
                    subindex Master_Index3018[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&motor4_control, NULL }
                     };

/* index 0x3019 :   Mapped variable motor4_status */
                    subindex Master_Index3019[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&motor4_status, NULL }
                     };

/* index 0x3020 :   Mapped variable motor4_mode */
                    subindex Master_Index3020[] = 
                     {
                       { RW, int8, sizeof (INTEGER8), (void*)&motor4_mode, NULL }
                     };

/* index 0x3021 :   Mapped variable motor4_mode_display */
                    subindex Master_Index3021[] = 
                     {
                       { RW, int8, sizeof (INTEGER8), (void*)&motor4_mode_display, NULL }
                     };

/* index 0x3022 :   Mapped variable motor4_position */
                    subindex Master_Index3022[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&motor4_position, NULL }
                     };

/* index 0x3023 :   Mapped variable motor4_velocity */
                    subindex Master_Index3023[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&motor4_velocity, NULL }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable Master_objdict[] = 
{
  { (subindex*)Master_Index1000,sizeof(Master_Index1000)/sizeof(Master_Index1000[0]), 0x1000},
  { (subindex*)Master_Index1001,sizeof(Master_Index1001)/sizeof(Master_Index1001[0]), 0x1001},
  { (subindex*)Master_Index1005,sizeof(Master_Index1005)/sizeof(Master_Index1005[0]), 0x1005},
  { (subindex*)Master_Index1006,sizeof(Master_Index1006)/sizeof(Master_Index1006[0]), 0x1006},
  { (subindex*)Master_Index1014,sizeof(Master_Index1014)/sizeof(Master_Index1014[0]), 0x1014},
  { (subindex*)Master_Index1018,sizeof(Master_Index1018)/sizeof(Master_Index1018[0]), 0x1018},
  { (subindex*)Master_Index1400,sizeof(Master_Index1400)/sizeof(Master_Index1400[0]), 0x1400},
  { (subindex*)Master_Index1401,sizeof(Master_Index1401)/sizeof(Master_Index1401[0]), 0x1401},
  { (subindex*)Master_Index1402,sizeof(Master_Index1402)/sizeof(Master_Index1402[0]), 0x1402},
  { (subindex*)Master_Index1403,sizeof(Master_Index1403)/sizeof(Master_Index1403[0]), 0x1403},
  { (subindex*)Master_Index1600,sizeof(Master_Index1600)/sizeof(Master_Index1600[0]), 0x1600},
  { (subindex*)Master_Index1601,sizeof(Master_Index1601)/sizeof(Master_Index1601[0]), 0x1601},
  { (subindex*)Master_Index1602,sizeof(Master_Index1602)/sizeof(Master_Index1602[0]), 0x1602},
  { (subindex*)Master_Index1603,sizeof(Master_Index1603)/sizeof(Master_Index1603[0]), 0x1603},
  { (subindex*)Master_Index1800,sizeof(Master_Index1800)/sizeof(Master_Index1800[0]), 0x1800},
  { (subindex*)Master_Index1801,sizeof(Master_Index1801)/sizeof(Master_Index1801[0]), 0x1801},
  { (subindex*)Master_Index1802,sizeof(Master_Index1802)/sizeof(Master_Index1802[0]), 0x1802},
  { (subindex*)Master_Index1803,sizeof(Master_Index1803)/sizeof(Master_Index1803[0]), 0x1803},
  { (subindex*)Master_Index1A00,sizeof(Master_Index1A00)/sizeof(Master_Index1A00[0]), 0x1A00},
  { (subindex*)Master_Index1A01,sizeof(Master_Index1A01)/sizeof(Master_Index1A01[0]), 0x1A01},
  { (subindex*)Master_Index1A02,sizeof(Master_Index1A02)/sizeof(Master_Index1A02[0]), 0x1A02},
  { (subindex*)Master_Index1A03,sizeof(Master_Index1A03)/sizeof(Master_Index1A03[0]), 0x1A03},
  { (subindex*)Master_Index3000,sizeof(Master_Index3000)/sizeof(Master_Index3000[0]), 0x3000},
  { (subindex*)Master_Index3001,sizeof(Master_Index3001)/sizeof(Master_Index3001[0]), 0x3001},
  { (subindex*)Master_Index3002,sizeof(Master_Index3002)/sizeof(Master_Index3002[0]), 0x3002},
  { (subindex*)Master_Index3003,sizeof(Master_Index3003)/sizeof(Master_Index3003[0]), 0x3003},
  { (subindex*)Master_Index3004,sizeof(Master_Index3004)/sizeof(Master_Index3004[0]), 0x3004},
  { (subindex*)Master_Index3005,sizeof(Master_Index3005)/sizeof(Master_Index3005[0]), 0x3005},
  { (subindex*)Master_Index3006,sizeof(Master_Index3006)/sizeof(Master_Index3006[0]), 0x3006},
  { (subindex*)Master_Index3007,sizeof(Master_Index3007)/sizeof(Master_Index3007[0]), 0x3007},
  { (subindex*)Master_Index3008,sizeof(Master_Index3008)/sizeof(Master_Index3008[0]), 0x3008},
  { (subindex*)Master_Index3009,sizeof(Master_Index3009)/sizeof(Master_Index3009[0]), 0x3009},
  { (subindex*)Master_Index3010,sizeof(Master_Index3010)/sizeof(Master_Index3010[0]), 0x3010},
  { (subindex*)Master_Index3011,sizeof(Master_Index3011)/sizeof(Master_Index3011[0]), 0x3011},
  { (subindex*)Master_Index3012,sizeof(Master_Index3012)/sizeof(Master_Index3012[0]), 0x3012},
  { (subindex*)Master_Index3013,sizeof(Master_Index3013)/sizeof(Master_Index3013[0]), 0x3013},
  { (subindex*)Master_Index3014,sizeof(Master_Index3014)/sizeof(Master_Index3014[0]), 0x3014},
  { (subindex*)Master_Index3015,sizeof(Master_Index3015)/sizeof(Master_Index3015[0]), 0x3015},
  { (subindex*)Master_Index3016,sizeof(Master_Index3016)/sizeof(Master_Index3016[0]), 0x3016},
  { (subindex*)Master_Index3017,sizeof(Master_Index3017)/sizeof(Master_Index3017[0]), 0x3017},
  { (subindex*)Master_Index3018,sizeof(Master_Index3018)/sizeof(Master_Index3018[0]), 0x3018},
  { (subindex*)Master_Index3019,sizeof(Master_Index3019)/sizeof(Master_Index3019[0]), 0x3019},
  { (subindex*)Master_Index3020,sizeof(Master_Index3020)/sizeof(Master_Index3020[0]), 0x3020},
  { (subindex*)Master_Index3021,sizeof(Master_Index3021)/sizeof(Master_Index3021[0]), 0x3021},
  { (subindex*)Master_Index3022,sizeof(Master_Index3022)/sizeof(Master_Index3022[0]), 0x3022},
  { (subindex*)Master_Index3023,sizeof(Master_Index3023)/sizeof(Master_Index3023[0]), 0x3023},
};

const indextable * Master_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode)
{
	(void)d;
	int i;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1005: i = 2;break;
		case 0x1006: i = 3;break;
		case 0x1014: i = 4;break;
		case 0x1018: i = 5;break;
		case 0x1400: i = 6;break;
		case 0x1401: i = 7;break;
		case 0x1402: i = 8;break;
		case 0x1403: i = 9;break;
		case 0x1600: i = 10;break;
		case 0x1601: i = 11;break;
		case 0x1602: i = 12;break;
		case 0x1603: i = 13;break;
		case 0x1800: i = 14;break;
		case 0x1801: i = 15;break;
		case 0x1802: i = 16;break;
		case 0x1803: i = 17;break;
		case 0x1A00: i = 18;break;
		case 0x1A01: i = 19;break;
		case 0x1A02: i = 20;break;
		case 0x1A03: i = 21;break;
		case 0x3000: i = 22;break;
		case 0x3001: i = 23;break;
		case 0x3002: i = 24;break;
		case 0x3003: i = 25;break;
		case 0x3004: i = 26;break;
		case 0x3005: i = 27;break;
		case 0x3006: i = 28;break;
		case 0x3007: i = 29;break;
		case 0x3008: i = 30;break;
		case 0x3009: i = 31;break;
		case 0x3010: i = 32;break;
		case 0x3011: i = 33;break;
		case 0x3012: i = 34;break;
		case 0x3013: i = 35;break;
		case 0x3014: i = 36;break;
		case 0x3015: i = 37;break;
		case 0x3016: i = 38;break;
		case 0x3017: i = 39;break;
		case 0x3018: i = 40;break;
		case 0x3019: i = 41;break;
		case 0x3020: i = 42;break;
		case 0x3021: i = 43;break;
		case 0x3022: i = 44;break;
		case 0x3023: i = 45;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &Master_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status Master_PDO_status[4] = {s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

const quick_index Master_firstIndex = {
  0, /* SDO_SVR */
  0, /* SDO_CLT */
  6, /* PDO_RCV */
  10, /* PDO_RCV_MAP */
  14, /* PDO_TRS */
  18 /* PDO_TRS_MAP */
};

const quick_index Master_lastIndex = {
  0, /* SDO_SVR */
  0, /* SDO_CLT */
  9, /* PDO_RCV */
  13, /* PDO_RCV_MAP */
  17, /* PDO_TRS */
  21 /* PDO_TRS_MAP */
};

const UNS16 Master_ObjdictSize = sizeof(Master_objdict)/sizeof(Master_objdict[0]); 

CO_Data Master_Data = CANOPEN_NODE_DATA_INITIALIZER(Master);

