
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef MASTER_H
#define MASTER_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 Master_valueRangeTest (UNS8 typeValue, void * value);
const indextable * Master_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode);

/* Master node data struct */
extern CO_Data Master_Data;
extern UNS16 motor1_control;		/* Mapped at index 0x3000, subindex 0x00*/
extern UNS16 motor1_status;		/* Mapped at index 0x3001, subindex 0x00*/
extern INTEGER8 motor1_mode;		/* Mapped at index 0x3002, subindex 0x00*/
extern INTEGER8 motor1_mode_display;		/* Mapped at index 0x3003, subindex 0x00*/
extern INTEGER32 motor1_position;		/* Mapped at index 0x3004, subindex 0x00*/
extern INTEGER32 motor1_velocity;		/* Mapped at index 0x3005, subindex 0x00*/
extern UNS16 motor2_control;		/* Mapped at index 0x3006, subindex 0x00*/
extern UNS16 motor2_status;		/* Mapped at index 0x3007, subindex 0x00*/
extern INTEGER8 motor2_mode;		/* Mapped at index 0x3008, subindex 0x00*/
extern INTEGER8 motor2_mode_display;		/* Mapped at index 0x3009, subindex 0x00*/
extern INTEGER32 motor2_position;		/* Mapped at index 0x3010, subindex 0x00*/
extern INTEGER32 motor2_velocity;		/* Mapped at index 0x3011, subindex 0x00*/
extern UNS16 motor3_control;		/* Mapped at index 0x3012, subindex 0x00*/
extern UNS16 motor3_status;		/* Mapped at index 0x3013, subindex 0x00*/
extern INTEGER8 motor3_mode;		/* Mapped at index 0x3014, subindex 0x00*/
extern INTEGER8 motor3_mode_display;		/* Mapped at index 0x3015, subindex 0x00*/
extern INTEGER32 motor3_position;		/* Mapped at index 0x3016, subindex 0x00*/
extern INTEGER32 motor3_velocity;		/* Mapped at index 0x3017, subindex 0x00*/
extern UNS16 motor4_control;		/* Mapped at index 0x3018, subindex 0x00*/
extern UNS16 motor4_status;		/* Mapped at index 0x3019, subindex 0x00*/
extern INTEGER8 motor4_mode;		/* Mapped at index 0x3020, subindex 0x00*/
extern INTEGER8 motor4_mode_display;		/* Mapped at index 0x3021, subindex 0x00*/
extern INTEGER32 motor4_position;		/* Mapped at index 0x3022, subindex 0x00*/
extern INTEGER32 motor4_velocity;		/* Mapped at index 0x3023, subindex 0x00*/

#endif // MASTER_H
