
/* File generated by gen_cfile.py. Should not be modified. */

#include "Master.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS16 Controlword = 0x0;		/* Mapped at index 0x6040, subindex 0x00 */
UNS16 Statusword = 0x0;		/* Mapped at index 0x6041, subindex 0x00 */
INTEGER8 Modes_of_operation = 0x0;		/* Mapped at index 0x6060, subindex 0x00 */
INTEGER8 Modes_of_operation_display = 0x0;		/* Mapped at index 0x6061, subindex 0x00 */
INTEGER32 Position_actual_value = 0x0;		/* Mapped at index 0x6064, subindex 0x00 */
INTEGER32 Velocity_actual_value = 0x0;		/* Mapped at index 0x606C, subindex 0x00 */
INTEGER32 Target_position = 0x0;		/* Mapped at index 0x607A, subindex 0x00 */
INTEGER32 Target_velocity = 0x0;		/* Mapped at index 0x60FF, subindex 0x00 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 Master_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 Master_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 Master_iam_a_slave = 0;

TIMER_HANDLE Master_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 Master_obj1000 = 0x0;	/* 0 */
                    subindex Master_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1000, NULL }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 Master_obj1001 = 0x0;	/* 0 */
                    subindex Master_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_obj1001, NULL }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 Master_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 Master_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    subindex Master_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1003, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1003[0], NULL }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 Master_obj1005 = 0x40000080;	/* 1073741952 */
                    subindex Master_Index1005[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1005, NULL }
                     };

/* index 0x1006 :   Communication / Cycle Period. */
                    UNS32 Master_obj1006 = 0x3D090;	/* 250000 */
                    subindex Master_Index1006[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1006, NULL }
                     };

/* index 0x100C :   Guard Time */ 
                    UNS16 Master_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 Master_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID. */
                    UNS32 Master_obj1014 = 0x80;	/* 128 */
                    subindex Master_Index1014[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1014, NULL }
                     };

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 Master_highestSubIndex_obj1016 = 0;
                    UNS32 Master_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time */ 
                    UNS16 Master_obj1017 = 0x0;   /* 0 */

/* index 0x1018 :   Identity. */
                    UNS8 Master_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 Master_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 Master_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 Master_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 Master_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex Master_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1018, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1018_Vendor_ID, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1018_Product_Code, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1018_Revision_Number, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1018_Serial_Number, NULL }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 Master_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1400_COB_ID_used_by_PDO = 0x204;	/* 516 */
                    UNS8 Master_obj1400_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 Master_obj1400_Inhibit_Time = 0xA;	/* 10 */
                    UNS8 Master_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1400, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1400_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1400_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1400_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1400_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1400_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1400_SYNC_start_value, NULL }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 Master_highestSubIndex_obj1401 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1401_COB_ID_used_by_PDO = 0x303;	/* 771 */
                    UNS8 Master_obj1401_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 Master_obj1401_Inhibit_Time = 0xA;	/* 10 */
                    UNS8 Master_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1401_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1401_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1401, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1401_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1401_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1401_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1401_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1401_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1401_SYNC_start_value, NULL }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 Master_highestSubIndex_obj1600 = 3; /* number of subindex - 1*/
                    UNS32 Master_obj1600[] = 
                    {
                      0x60400010,	/* 1614807056 */
                      0x60600008,	/* 1616904200 */
                      0x60FF0020	/* 1627324448 */
                    };
                    subindex Master_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1600, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1600[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1600[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1600[2], NULL }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 Master_highestSubIndex_obj1601 = 3; /* number of subindex - 1*/
                    UNS32 Master_obj1601[] = 
                    {
                      0x60400010,	/* 1614807056 */
                      0x60600008,	/* 1616904200 */
                      0x60FF0020	/* 1627324448 */
                    };
                    subindex Master_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1601, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1601[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1601[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1601[2], NULL }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 Master_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1800_COB_ID_used_by_PDO = 0x184;	/* 388 */
                    UNS8 Master_obj1800_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 Master_obj1800_Inhibit_Time = 0xA;	/* 10 */
                    UNS8 Master_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1800_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1800_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1800, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1800_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1800_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1800_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1800_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1800_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1800_SYNC_start_value, NULL }
                     };

/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 Master_highestSubIndex_obj1801 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1801_COB_ID_used_by_PDO = 0x283;	/* 643 */
                    UNS8 Master_obj1801_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 Master_obj1801_Inhibit_Time = 0xA;	/* 10 */
                    UNS8 Master_obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1801_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1801_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1801[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1801, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1801_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1801_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1801_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1801_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1801_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1801_SYNC_start_value, NULL }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 Master_highestSubIndex_obj1A00 = 3; /* number of subindex - 1*/
                    UNS32 Master_obj1A00[] = 
                    {
                      0x60410010,	/* 1614872592 */
                      0x60610008,	/* 1616969736 */
                      0x606C0020	/* 1617690656 */
                    };
                    subindex Master_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1A00, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A00[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A00[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A00[2], NULL }
                     };

/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 Master_highestSubIndex_obj1A01 = 3; /* number of subindex - 1*/
                    UNS32 Master_obj1A01[] = 
                    {
                      0x60410010,	/* 1614872592 */
                      0x60610008,	/* 1616969736 */
                      0x606C0020	/* 1617690656 */
                    };
                    subindex Master_Index1A01[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1A01, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A01[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A01[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A01[2], NULL }
                     };

/* index 0x6040 :   Mapped variable Controlword */
                    subindex Master_Index6040[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Controlword, NULL }
                     };

/* index 0x6041 :   Mapped variable Statusword */
                    subindex Master_Index6041[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&Statusword, NULL }
                     };

/* index 0x6060 :   Mapped variable Modes of operation */
                    subindex Master_Index6060[] = 
                     {
                       { RW, int8, sizeof (INTEGER8), (void*)&Modes_of_operation, NULL }
                     };

/* index 0x6061 :   Mapped variable Modes of operation display */
                    subindex Master_Index6061[] = 
                     {
                       { RO, int8, sizeof (INTEGER8), (void*)&Modes_of_operation_display, NULL }
                     };

/* index 0x6064 :   Mapped variable Position actual value */
                    subindex Master_Index6064[] = 
                     {
                       { RO, int32, sizeof (INTEGER32), (void*)&Position_actual_value, NULL }
                     };

/* index 0x606C :   Mapped variable Velocity actual value */
                    subindex Master_Index606C[] = 
                     {
                       { RO, int32, sizeof (INTEGER32), (void*)&Velocity_actual_value, NULL }
                     };

/* index 0x607A :   Mapped variable Target position */
                    subindex Master_Index607A[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&Target_position, NULL }
                     };

/* index 0x60FF :   Mapped variable Target velocity */
                    subindex Master_Index60FF[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&Target_velocity, NULL }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable Master_objdict[] = 
{
  { (subindex*)Master_Index1000,sizeof(Master_Index1000)/sizeof(Master_Index1000[0]), 0x1000},
  { (subindex*)Master_Index1001,sizeof(Master_Index1001)/sizeof(Master_Index1001[0]), 0x1001},
  { (subindex*)Master_Index1005,sizeof(Master_Index1005)/sizeof(Master_Index1005[0]), 0x1005},
  { (subindex*)Master_Index1006,sizeof(Master_Index1006)/sizeof(Master_Index1006[0]), 0x1006},
  { (subindex*)Master_Index1014,sizeof(Master_Index1014)/sizeof(Master_Index1014[0]), 0x1014},
  { (subindex*)Master_Index1018,sizeof(Master_Index1018)/sizeof(Master_Index1018[0]), 0x1018},
  { (subindex*)Master_Index1400,sizeof(Master_Index1400)/sizeof(Master_Index1400[0]), 0x1400},
  { (subindex*)Master_Index1401,sizeof(Master_Index1401)/sizeof(Master_Index1401[0]), 0x1401},
  { (subindex*)Master_Index1600,sizeof(Master_Index1600)/sizeof(Master_Index1600[0]), 0x1600},
  { (subindex*)Master_Index1601,sizeof(Master_Index1601)/sizeof(Master_Index1601[0]), 0x1601},
  { (subindex*)Master_Index1800,sizeof(Master_Index1800)/sizeof(Master_Index1800[0]), 0x1800},
  { (subindex*)Master_Index1801,sizeof(Master_Index1801)/sizeof(Master_Index1801[0]), 0x1801},
  { (subindex*)Master_Index1A00,sizeof(Master_Index1A00)/sizeof(Master_Index1A00[0]), 0x1A00},
  { (subindex*)Master_Index1A01,sizeof(Master_Index1A01)/sizeof(Master_Index1A01[0]), 0x1A01},
  { (subindex*)Master_Index6040,sizeof(Master_Index6040)/sizeof(Master_Index6040[0]), 0x6040},
  { (subindex*)Master_Index6041,sizeof(Master_Index6041)/sizeof(Master_Index6041[0]), 0x6041},
  { (subindex*)Master_Index6060,sizeof(Master_Index6060)/sizeof(Master_Index6060[0]), 0x6060},
  { (subindex*)Master_Index6061,sizeof(Master_Index6061)/sizeof(Master_Index6061[0]), 0x6061},
  { (subindex*)Master_Index6064,sizeof(Master_Index6064)/sizeof(Master_Index6064[0]), 0x6064},
  { (subindex*)Master_Index606C,sizeof(Master_Index606C)/sizeof(Master_Index606C[0]), 0x606C},
  { (subindex*)Master_Index607A,sizeof(Master_Index607A)/sizeof(Master_Index607A[0]), 0x607A},
  { (subindex*)Master_Index60FF,sizeof(Master_Index60FF)/sizeof(Master_Index60FF[0]), 0x60FF},
};

const indextable * Master_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode)
{
	(void)d;
	int i;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1005: i = 2;break;
		case 0x1006: i = 3;break;
		case 0x1014: i = 4;break;
		case 0x1018: i = 5;break;
		case 0x1400: i = 6;break;
		case 0x1401: i = 7;break;
		case 0x1600: i = 8;break;
		case 0x1601: i = 9;break;
		case 0x1800: i = 10;break;
		case 0x1801: i = 11;break;
		case 0x1A00: i = 12;break;
		case 0x1A01: i = 13;break;
		case 0x6040: i = 14;break;
		case 0x6041: i = 15;break;
		case 0x6060: i = 16;break;
		case 0x6061: i = 17;break;
		case 0x6064: i = 18;break;
		case 0x606C: i = 19;break;
		case 0x607A: i = 20;break;
		case 0x60FF: i = 21;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &Master_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status Master_PDO_status[2] = {s_PDO_status_Initializer,s_PDO_status_Initializer};

const quick_index Master_firstIndex = {
  0, /* SDO_SVR */
  0, /* SDO_CLT */
  6, /* PDO_RCV */
  8, /* PDO_RCV_MAP */
  10, /* PDO_TRS */
  12 /* PDO_TRS_MAP */
};

const quick_index Master_lastIndex = {
  0, /* SDO_SVR */
  0, /* SDO_CLT */
  7, /* PDO_RCV */
  9, /* PDO_RCV_MAP */
  11, /* PDO_TRS */
  13 /* PDO_TRS_MAP */
};

const UNS16 Master_ObjdictSize = sizeof(Master_objdict)/sizeof(Master_objdict[0]); 

CO_Data Master_Data = CANOPEN_NODE_DATA_INITIALIZER(Master);

